// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myProject.Models;

public partial class Member
{
    public int Id { get; set; }

    public string F_name { get; set; }

    public string L_name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Address { get; set; }

    public string Role { get; set; }

    public int? Age { get; set; }

    public int PhoneNumber { get; set; }

    public bool isDeleted { get; set; }

    public virtual ICollection<Pet> Pets { get; set; } = new List<Pet>();
}