// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myProject.Models;

public partial class Pet
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Species { get; set; }

    public string Gender { get; set; }

    public string Color { get; set; }

    public bool AdoptionStatus { get; set; }

    public DateTime DateAdded { get; set; }

    public string Description { get; set; }

    public int? AdopterId { get; set; }

    public string Age { get; set; }

    public string Breed { get; set; }

    public virtual Member Adopter { get; set; }
}